export const CONFIG = {
  content: "Thanks for using Legit Popper. Your custom content goes here.",
  showWhen: 0,
  timeUntil: null,
  onlyOnce: false,
  closeButton: true,
  closeButtonPosition: "right",
  position: "br",
  bgColor: "#fff",
  textColor: "#444",
  borderWidth: 1,
  borderColor: "#d6d6d6",
  borderRadius: 3,
  boxShadow: true,
  width: 0,
  fullWidth: false,
  padding: 20,
};
